/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unir.plataformasdedesarrollo.actividad_1.frames;

import com.unir.plataformasdedesarrollo.actividad_1.entidades.Pedido;
import javax.swing.JOptionPane;

/**
 *
 * @author julia
 */
public class ResumenPedido extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ResumenPedido(Pedido pedido) {
        initComponents();
        distribuidorLbl.setText(pedido.getProovedor());
        setTitle(pedido.getProovedor());
        resumenLbl.setText(pedido.getCantidad() + " unidades del " + pedido.getMedicamento().getTipo() + " - " + pedido.getMedicamento().getNombre());
        detalleLbl.setText("Para la farmacia situada en " + pedido.getSucursal().getNombre() + " : " + pedido.getSucursal().getDireccion());
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        distribuidorLbl = new javax.swing.JLabel();
        resumenLbl = new javax.swing.JLabel();
        cancelarBtn = new javax.swing.JButton();
        enviarBtn = new javax.swing.JButton();
        detalleLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        distribuidorLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        distribuidorLbl.setText("DISTRIBUIDOR");

        resumenLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resumenLbl.setText("X unidades del tipo y nombre");

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        enviarBtn.setText("Enviar");
        enviarBtn.setActionCommand("enviarBtn");
        enviarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarBtnActionPerformed(evt);
            }
        });

        detalleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detalleLbl.setText("X unidades del tipo y nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enviarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(distribuidorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(resumenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(detalleLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(distribuidorLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resumenLbl)
                .addGap(26, 26, 26)
                .addComponent(detalleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarBtnActionPerformed
        System.out.println("Pedido enviado");        // TODO add your handling code here:
        setVisible(false);

    }//GEN-LAST:event_enviarBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JLabel detalleLbl;
    private javax.swing.JLabel distribuidorLbl;
    private javax.swing.JButton enviarBtn;
    private javax.swing.JLabel resumenLbl;
    // End of variables declaration//GEN-END:variables
}
